# Generated by Django 5.1.6 on 2025-02-07 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_source_id', models.CharField(max_length=255, unique=True)),
                ('ad_account_id', models.CharField(max_length=255)),
                ('platform', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TrafficSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tag', models.CharField(max_length=255, unique=True)),
                ('disregarded', models.BooleanField(default=False)),
                ('organic', models.BooleanField(default=False)),
                ('creation_date', models.DateTimeField()),
                ('ad_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='main.adsource')),
                ('traffic_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='main.trafficsource')),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('external_id', models.CharField(max_length=255, unique=True)),
                ('creation_date', models.DateTimeField()),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('ips', models.JSONField(blank=True, default=list)),
                ('phone_numbers', models.JSONField(blank=True, default=list)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('first_source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_leads', to='main.source')),
                ('last_source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_leads', to='main.source')),
            ],
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('creation_date', models.DateTimeField()),
                ('ad_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='main.adsource')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='main.source')),
            ],
        ),
    ]
