# Generated by Django 5.1.6 on 2025-02-07 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='creation_date',
            field=models.CharField(blank=True, null=True),
        ),
    ]
