# Generated by Django 5.1.6 on 2025-02-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_ad_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='creation_date',
            field=models.CharField(blank=True, null=True),
        ),
    ]
