# Generated by Django 5.1.6 on 2025-02-07 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_lead_creation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='ad_source',
        ),
    ]
