# Generated by Django 5.1.6 on 2025-02-12 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdAccountAtrribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aa_id', models.CharField(max_length=50)),
                ('clicks', models.CharField(max_length=50)),
                ('cost', models.CharField(max_length=50)),
                ('cost_per_click', models.CharField(max_length=50)),
                ('cost_per_lead', models.CharField(max_length=50)),
                ('cost_per_sale', models.FloatField(blank=True, default=0, null=True)),
                ('cost_per_unique_sales', models.CharField(max_length=50)),
                ('average_order_value', models.FloatField(blank=True, default=0, null=True)),
                ('ctr', models.CharField(max_length=50)),
                ('impressions', models.IntegerField(blank=True, default=0, null=True)),
                ('leads', models.IntegerField(blank=True, default=0, null=True)),
                ('profit', models.FloatField(blank=True, default=0, null=True)),
                ('roas', models.IntegerField(blank=True, default=0, null=True)),
                ('sales', models.IntegerField(blank=True, default=0, null=True)),
                ('total_revenue', models.FloatField(blank=True, default=0, null=True)),
                ('unique_sales', models.IntegerField(blank=True, default=0, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
