# Generated by Django 5.1.6 on 2025-02-12 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_adaccountatrribution'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adaccountatrribution',
            old_name='aa_id',
            new_name='attr_id',
        ),
        migrations.AddField(
            model_name='adaccountatrribution',
            name='ad_source',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='att_adsources', to='main.adsource'),
            preserve_default=False,
        ),
    ]
