# Generated by Django 5.1.6 on 2025-02-12 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_aa_id_adaccountatrribution_attr_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adaccountatrribution',
            name='attr_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adaccountatrribution',
            name='clicks',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adaccountatrribution',
            name='cost',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adaccountatrribution',
            name='cost_per_click',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adaccountatrribution',
            name='cost_per_lead',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adaccountatrribution',
            name='cost_per_unique_sales',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adaccountatrribution',
            name='ctr',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adsource',
            name='platform',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
