# Generated by Django 5.1.6 on 2025-02-12 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_adaccountatrribution_attr_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adaccountatrribution',
            name='attribution_model',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
