# Generated by Django 5.1.6 on 2025-02-26 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_adaccountatrribution_average_order_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='adaccattr',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_adattr', to='main.adaccountatrribution'),
        ),
        migrations.AddField(
            model_name='ad',
            name='adsource',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_adsrc', to='main.adsource'),
        ),
    ]
