# Generated by Django 5.1.6 on 2025-02-14 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scriptdata', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adscript',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='adscript',
            old_name='name',
            new_name='filename',
        ),
        migrations.RemoveField(
            model_name='adscript',
            name='file',
        ),
        migrations.RemoveField(
            model_name='adscript',
            name='text_content',
        ),
        migrations.AddField(
            model_name='adscript',
            name='ad_file',
            field=models.FileField(default='', upload_to='adscripts/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adscript',
            name='ad_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='adscript',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adscript',
            name='industry',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='adscript',
            name='platform',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
