# Generated by Django 5.1.6 on 2025-02-24 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scriptdata', '0002_rename_uploaded_at_adscript_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adscript',
            name='file_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
